# run brew bundle to install these

brew "bat"
brew "eza"
brew "fzf"
brew "mise"
brew "stow"
brew "thefuck"
brew "zoxide"
brew "libyaml"
brew "zlib"
cask "1password"
cask "1password-cli"
cask "adobe-creative-cloud"
cask "arc"
cask "claude"
cask "font-meslo-lg-nerd-font"
cask "raycast"
cask "wezterm"
cask "zed"
